kind: Deployment
apiVersion: apps/v1
metadata:
   name: devops
spec:
   replicas: 2
   selector:      # tells the controller which pod
    matchLabels:
     app: devops
   template:
      metadata:
        labels:
          app: devops
      spec:
       containers:
        - name: devops
          image: yasin407/devops
          imagePullPolicy: Always
          ports:
          - containerPort: 80